---
  AWSTemplateFormatVersion: '2010-09-09'

  Description: Bucket Antivirus Quickstart Template

  Resources:

    lambdaAVUpdateDefinitions:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: lambda-en1-t-av-update-definitions
        Description: LambdaFunction to update the AntiVirus definitions in the AV Definitions bucket.
        Runtime: python3.7
        Code:
          ZipFile: |
            import json
            def lambda_handler(event, context):
                return {
                    'statusCode': 200, 'body': json.dumps('Hello from Lambda!')
                }
        Handler: "update.lambda_handler"
        MemorySize: 1024
        Timeout: 300
        Role: arn:aws:iam::880900201349:role/service-role/lambda-en1-t-av-update-definitions-role-kyjzcjof
        Environment:
          Variables:
            AV_DEFINITION_S3_BUCKET: bucket-en1-t-files-private.dev.hokify.com
        Tags:
          - Key: Service
            Value: bucket-antivirus

    lambdaAVUpdateDefinitionsSchedule:
      Type: "AWS::Events::Rule"
      DependsOn:
        - lambdaAVUpdateDefinitions
      Properties:
        Name: lambda-en1-t-av-update-definitions-schedule
        Description: A schedule for the AV Update Definitions Lambda function.
        ScheduleExpression: rate(3 hours)
        State: ENABLED
        Targets:
          - Arn: !Sub ${lambdaAVUpdateDefinitions.Arn}
            Id: lambdaAVUpdateDefinitionsSchedule

    lambdaAVUpdateDefinitionsSchedulePermission:
      Type: "AWS::Lambda::Permission"
      DependsOn:
        - lambdaAVUpdateDefinitionsSchedule
      Properties:
        Action: 'lambda:InvokeFunction'
        FunctionName: !Sub ${lambdaAVUpdateDefinitions.Arn}
        Principal: 'events.amazonaws.com'
        SourceArn: !Sub ${lambdaAVUpdateDefinitionsSchedule.Arn}

    lambdaAVScanner:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: lambda-en1-t-av-scanner
        Description: LambdaFunction to scan newly uploaded objects in S3.
        Runtime: python3.7
        Code:
          ZipFile: |
            import json
            def lambda_handler(event, context):
                return {
                    'statusCode': 200, 'body': json.dumps('Hello from Lambda!')
                }
        Handler: "scan.lambda_handler"
        MemorySize: 1500
        Timeout: 300
        Role: arn:aws:iam::880900201349:role/service-role/lambda-en1-t-av-scan-role-kgugaj5e
        Environment:
          Variables:
            AV_DEFINITION_S3_BUCKET: bucket-en1-t-files-private
        Tags:
          - Key: Service
            Value: bucket-antivirus



  Outputs:

    lambdaAVUpdateDefinitions:
      Value: !Ref lambdaAVUpdateDefinitions
      Description: Lambda function to update the Antivirus Definitions in its respective bucket

    lambdaAVScanner:
      Value: !Ref lambdaAVScanner
      Description: Lambda function to scan newly created S3 objects
